### ISSUE TITLE
Integration into Euroe

### ISSUE THREAD

**Issue by bm777** [valentinmadrid/plancian#5]
@valentinmadrid 

How can I integrate also euroe stable coin as you did with USDC into Solanapay?

I succeeded in doing what you did here, I would like to integrate euroe into Solanapay
ref: [https://www.euroe.com/blog/solana](https://www.euroe.com/blog/solana)

**Comment by valentinmadrid** [comment]
Hey, you can add the splToken mint Adress to the qr code Generation and you should be good.

**Comment by bm777** [comment]
okay, thank you. I will try it.

**Comment by bm777** [comment]
It works
@valentinmadrid
